/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicControlsZoo: typeof import('./../components/controls/BasicControlsZoo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    XButton: typeof import('./../components/controls/XButton.vue')['default']
    XButtonGroup: typeof import('./../components/controls/XButtonGroup.vue')['default']
    XCard: typeof import('./../components/controls/XCard.vue')['default']
    XCheckbox: typeof import('./../components/controls/XCheckbox.vue')['default']
    XChip: typeof import('./../components/controls/XChip.vue')['default']
    XCollapseItem: typeof import('./../components/controls/XCollapseItem.vue')['default']
    XDialog: typeof import('./../components/controls/XDialog.vue')['default']
    XDialogBody: typeof import('./../components/controls/XDialogBody.vue')['default']
    XDialogContent: typeof import('./../components/controls/XDialogContent.vue')['default']
    XDialogFooter: typeof import('./../components/controls/XDialogFooter.vue')['default']
    XDialogHeader: typeof import('./../components/controls/XDialogHeader.vue')['default']
    XDialogTitlebar: typeof import('./../components/controls/XDialogTitlebar.vue')['default']
    XDialogWindow: typeof import('./../components/controls/XDialogWindow.vue')['default']
    XDropdown: typeof import('./../components/controls/XDropdown.vue')['default']
    XIcon: typeof import('./../components/controls/XIcon.vue')['default']
    XInput: typeof import('./../components/controls/XInput.vue')['default']
    XListItem: typeof import('./../components/controls/XListItem.vue')['default']
    XListView: typeof import('./../components/controls/XListView.vue')['default']
    XRadioButton: typeof import('./../components/controls/XRadioButton.vue')['default']
    XRange: typeof import('./../components/controls/XRange.vue')['default']
    XSelect: typeof import('./../components/controls/XSelect.vue')['default']
    XSidebarButton: typeof import('./../components/controls/XSidebarButton.vue')['default']
    XSlider: typeof import('./../components/controls/XSlider.vue')['default']
    XStepper: typeof import('./../components/controls/XStepper.vue')['default']
    XSwitch: typeof import('./../components/controls/XSwitch.vue')['default']
    XTab: typeof import('./../components/controls/XTab.vue')['default']
    XTabs: typeof import('./../components/controls/XTabs.vue')['default']
    XWell: typeof import('./../components/controls/XWell.vue')['default']
  }
}
